import { loadImage } from "../world/compose";
import { bodyCut } from "./bodysegment";
import { faceBox, subjectMask } from "./segment";
import { SCENES, placeSubject, sceneSrc, type SceneId } from "./scenes";
import { styliseImageData, FINE, type StyliseOptions } from "./stylise";
import { gradeFor, gradePixels } from "./timeofday";

/**
 * One photograph in, one painted frame of the city out.
 *
 * The person is found, painted, and **placed into a scene** — a beach, a neon promenade, a marina, a
 * rooftop pool, a palm boulevard. Those are real plates generated by the local model
 * (`tools/print-desk/scenes.mjs`) and committed, so this is a composite into a place, not a recolour
 * of a photograph on a gradient.
 *
 * The subject is painted from a **crop of themselves**, not from the whole frame. A person occupying a
 * tenth of a 6000px photograph is 600 pixels of detail spread across a 1600px frame — painted at that
 * scale they come out as mush. Cropped and painted at their own resolution they keep their detail, and
 * only then are they scaled into the scene.
 */

export interface PortraitOptions extends StyliseOptions {
  scene?: SceneId;
  /** The look by id — which hour of the day the *world* is graded to, not just the person. */
  look?: string;
  /**
   * More work for a better frame: a larger output, the subject painted at a higher minimum
   * resolution, a supersampled composite, and the colour work from `FINE` instead of the look's own.
   * Roughly three times the compute.
   */
  fine?: boolean;
  /** Skip the cut-out and paint the whole frame (the fallback, and the 'no person found' path). */
  wholeFrame?: boolean;
  /** Longest edge of the output, in pixels. Defaults by finish: 2200 fine, 1600 fast. */
  maxSize?: number;
  /** Called as each stage begins, for an honest progress line. */
  onStage?: (stage: string) => void;
}

export interface PortraitResult {
  canvas: HTMLCanvasElement;
  /** Fraction of the frame the subject covered in the photograph, 0..1. */
  share: number;
  /** True when the subject was cut out and placed; false when the whole frame was painted. */
  cutOut: boolean;
  /** Who found the person: the segmentation model, the classic region find, or nobody. */
  cutSource: "model" | "classic" | "none";
  scene: SceneId;
}

/** The smallest edge the subject's crop is painted at, before the paint stops seeing detail. */
const MIN_PAINT_EDGE = 900;

function canvasOf(width: number, height: number): { canvas: HTMLCanvasElement; ctx: CanvasRenderingContext2D } {
  const canvas = document.createElement("canvas");
  canvas.width = Math.max(1, Math.round(width));
  canvas.height = Math.max(1, Math.round(height));
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("this browser has no 2d canvas context");
  return { canvas, ctx };
}

export async function portraitFromImage(
  image: CanvasImageSource & { width: number; height: number },
  options: PortraitOptions = {},
): Promise<PortraitResult> {
  const { scene = "beach", wholeFrame = false, maxSize, look, fine = false, onStage, ...style } = options;
  const plate = SCENES[scene] ?? SCENES.beach;

  // The finish decides the sizes. Fine prints bigger, paints the subject's crop at a higher minimum
  // resolution, and composites at 1.5× before scaling down — the extra samples are what take the
  // jagged edge off a cut-out and let the subject's own colours survive the move into the scene.
  const outLong = Math.round(maxSize ?? (fine ? 2200 : 1600));
  const paintEdge = fine ? 1200 : MIN_PAINT_EDGE;
  const supersample = fine ? 1.5 : 1;
  const paintOptions = fine ? { ...style, ...FINE } : style;

  // A working size that does not depend on what came in: a 500px photograph and a 6000px one both get
  // a frame with room to see detail. This is the fix for tiny images and for large ones whose subject
  // is small in the frame.
  const photoScale = Math.min(1, outLong / Math.max(image.width, image.height));
  const workW = Math.max(320, Math.round(image.width * photoScale));
  const workH = Math.max(320, Math.round(image.height * photoScale));

  onStage?.("reading your photo");
  const photo = canvasOf(workW, workH);
  photo.ctx.drawImage(image, 0, 0, workW, workH);
  const frame = photo.ctx.getImageData(0, 0, workW, workH);

  let mask: Uint8ClampedArray | null = null;
  let box = { x: 0, y: 0, width: workW, height: workH };
  let share = 0;
  let cutSource: PortraitResult["cutSource"] = "none";
  if (!wholeFrame) {
    onStage?.("finding you in the frame");
    // The segmentation model first, because it is the difference between a cut-out and a recolour: it
    // reads a face in shadow, a subject at night, and hair against a busy wall. One 16MB download,
    // cached by the browser, no key, nothing uploaded.
    const cut = await bodyCut(photo.canvas, workW, workH, onStage);
    if (cut && cut.share > 0.012 && cut.share < 0.985) {
      mask = cut.alpha;
      box = cut.box;
      share = cut.share;
      cutSource = "model";
    } else {
      // The classic find, for the case where the model could not load. Good on a plain background, and
      // reported honestly when it is what did the work.
      const keep = await faceBox(image);
      const subject = subjectMask(frame.data, workW, workH, { keep });
      if (subject.share > 0.012 && subject.share < 0.985) {
        mask = subject.mask;
        box = subject.box;
        share = subject.share;
        cutSource = "classic";
      }
    }
  }

  // Paint the subject from their own crop, at their own resolution.
  onStage?.(fine ? "painting you in the city's light (fine: bigger, truer colour)" : "painting you in the city's light");
  const margin = Math.round(Math.max(box.width, box.height) * 0.14);
  const cropX = Math.max(0, box.x - margin);
  const cropY = Math.max(0, box.y - margin);
  const cropW = Math.min(workW - cropX, box.width + margin * 2);
  const cropH = Math.min(workH - cropY, box.height + margin * 2);

  const crop = canvasOf(cropW, cropH);
  crop.ctx.drawImage(photo.canvas, cropX, cropY, cropW, cropH, 0, 0, cropW, cropH);

  const shortEdge = Math.min(cropW, cropH);
  const upscale = shortEdge > 0 ? Math.max(1, paintEdge / shortEdge) : 1;
  const paintW = Math.round(cropW * upscale);
  const paintH = Math.round(cropH * upscale);

  let toPaint = crop.ctx.getImageData(0, 0, cropW, cropH).data;
  if (upscale > 1.01) {
    const big = canvasOf(paintW, paintH);
    big.ctx.imageSmoothingEnabled = true;
    big.ctx.imageSmoothingQuality = "high";
    big.ctx.drawImage(crop.canvas, 0, 0, cropW, cropH, 0, 0, paintW, paintH);
    toPaint = big.ctx.getImageData(0, 0, paintW, paintH).data;
  }

  const paintedPixels = styliseImageData(toPaint, paintW, paintH, {
    ...paintOptions,
    light: paintOptions.light ?? 0.22,
  });
  const painted = canvasOf(paintW, paintH);
  const paintedImage = painted.ctx.createImageData(paintW, paintH);
  paintedImage.data.set(paintedPixels);
  painted.ctx.putImageData(paintedImage, 0, 0);

  // The subject's own mask, cropped and scaled with them, so the cut survives the upscale.
  if (mask) {
    const maskCanvas = canvasOf(workW, workH);
    const maskData = maskCanvas.ctx.createImageData(workW, workH);
    for (let i = 0; i < mask.length; i += 1) maskData.data[i * 4 + 3] = mask[i];
    maskCanvas.ctx.putImageData(maskData, 0, 0);

    const cropMask = canvasOf(cropW, cropH);
    cropMask.ctx.drawImage(maskCanvas.canvas, cropX, cropY, cropW, cropH, 0, 0, cropW, cropH);

    const bigMask = canvasOf(paintW, paintH);
    bigMask.ctx.imageSmoothingEnabled = true;
    bigMask.ctx.imageSmoothingQuality = "high";
    bigMask.ctx.drawImage(cropMask.canvas, 0, 0, cropW, cropH, 0, 0, paintW, paintH);

    painted.ctx.save();
    painted.ctx.globalCompositeOperation = "destination-in";
    painted.ctx.drawImage(bigMask.canvas, 0, 0);
    painted.ctx.restore();
  }

  // The scene: a real plate, graded to the hour the visitor chose, cropped to the output's aspect.
  onStage?.(`setting the frame in ${plate.label.toLowerCase()}`);
  const outW = Math.round(outLong * supersample);
  const outH = Math.round(((outLong * 9) / 16) * supersample);
  const out = canvasOf(outW, outH);
  const grade = gradeFor(look ?? "dusk");
  try {
    const sceneImage = await loadImage(sceneSrc(scene));
    // Grade the plate itself. This is what makes "neon" or "night" a change to the world rather than a
    // tint on the person — the sky, the water and the wet asphalt all move together. Done at output
    // size: grading a 1344px plate is cheap, and the crop throws the extra pixels away anyway.
    const scaled = canvasOf(outW, outH);
    const sceneScale = Math.max(outW / sceneImage.width, outH / sceneImage.height);
    const drawW = sceneImage.width * sceneScale;
    const drawH = sceneImage.height * sceneScale;
    scaled.ctx.drawImage(sceneImage, (outW - drawW) / 2, (outH - drawH) / 2, drawW, drawH);
    const raw = scaled.ctx.getImageData(0, 0, outW, outH);
    raw.data.set(gradePixels(raw.data, grade));
    out.ctx.putImageData(raw, 0, 0);
  } catch {
    // No scene plate (offline, or a build shipped without the images): a dark ground keeps the subject
    // placed rather than lost.
    out.ctx.fillStyle = "#0b0a12";
    out.ctx.fillRect(0, 0, outW, outH);
  }

  // Centre-bottom, aspect preserved: the *crop* is placed and the subject inside it sets the scale, so
  // the margin around them is never compressed into a stretch.
  const placed = placeSubject(box, { x: cropX, y: cropY, width: cropW, height: cropH }, plate, {
    width: outW,
    height: outH,
  });
  const target = mask ? placed : { x: 0, y: 0, width: outW, height: outH };

  if (mask) {
    onStage?.("placing you in it");
    const shadow = out.ctx.createRadialGradient(
      target.x + target.width / 2,
      target.y + target.height,
      0,
      target.x + target.width / 2,
      target.y + target.height,
      Math.max(24, target.width * 1.3),
    );
    shadow.addColorStop(0, "rgba(4, 3, 10, 0.55)");
    shadow.addColorStop(1, "rgba(4, 3, 10, 0)");
    out.ctx.fillStyle = shadow;
    out.ctx.fillRect(target.x - target.width, target.y + target.height * 0.5, target.width * 3, target.height * 0.8);
  }

  out.ctx.drawImage(painted.canvas, target.x, target.y, target.width, target.height);

  if (mask) {
    onStage?.("matching the light");
    const fromRight = plate.light === "right";
    const rim = out.ctx.createLinearGradient(
      fromRight ? target.x + target.width : target.x,
      target.y,
      fromRight ? target.x : target.x + target.width,
      target.y + target.height,
    );
    rim.addColorStop(0, "rgba(255, 214, 150, 0.24)");
    rim.addColorStop(1, "rgba(255, 122, 61, 0)");
    out.ctx.save();
    out.ctx.globalCompositeOperation = "screen";
    out.ctx.fillStyle = rim;
    out.ctx.drawImage(painted.canvas, target.x, target.y, target.width, target.height);
    out.ctx.restore();
  }

  // Fine mode composited at 1.5×: scale down to the size the caller asked for first, so the grade runs
  // once, on the pixels that actually ship.
  const finalW = Math.round(outLong);
  const finalH = Math.round((outLong * 9) / 16);
  const final = canvasOf(finalW, finalH);
  final.ctx.imageSmoothingEnabled = true;
  final.ctx.imageSmoothingQuality = "high";
  final.ctx.drawImage(out.canvas, 0, 0, outW, outH, 0, 0, finalW, finalH);

  // The unifying pass: subject and place, one palette, one grain. Kept light on purpose — a heavy
  // second quantisation would repaint the plate's own detail away — and lighter still in fine mode,
  // where the whole point is that the colour came through.
  onStage?.(fine ? "grading the whole frame (fine)" : "grading the whole frame");
  const composed = final.ctx.getImageData(0, 0, finalW, finalH);
  const graded = styliseImageData(composed.data, finalW, finalH, {
    colours: 16,
    palette: 0.18,
    ink: 0.12,
    tone: style.tone ?? 0.45,
    light: 0,
    paper: fine ? (style.paper ?? 0.28) * 0.55 : (style.paper ?? 0.28),
    finish: style.finish ?? 0.5,
    smooth: 0,
    exposure: 0.35,
    seed: style.seed ?? 1,
  });
  const gradedImage = final.ctx.createImageData(finalW, finalH);
  gradedImage.data.set(graded);
  final.ctx.putImageData(gradedImage, 0, 0);

  return { canvas: final.canvas, share, cutOut: Boolean(mask), cutSource, scene };
}