import { useEffect, useRef, useState, type ReactElement } from "react";

/**
 * The film on the title sheet: the city plate being generated.
 *
 * Twelve cells of one sprite, dissolved one into the next — and the build is the plate's *layers*, in the
 * press's own order: the city's drawing, the hour's grade, the flat shapes, the ink lines, the detail, a fuller
 * palette, and the plate with its paper. Then the city at other hours. No faces: these are the plates the city
 * draws of itself. The frames were generated by `tools/make-film.mjs`, which calls this app's own `gradePixels`
 * and `styliseImageData`, so what the visitor watches is the pipeline rather than a picture of it.
 *
 * Full-bleed on purpose: the sheet's padding is undone so the film *is* the screen, and each cell is
 * cover-fitted, so it fills whatever viewport it lands on instead of letterboxing inside a mat. The step's name
 * is on screen while it happens — the point of the film is how a plate is generated.
 *
 * It cannot hold the entry hostage. If the sprite does not arrive within `GUARD_MS`, or fails, or the canvas is
 * unavailable, `onDone` fires and the title gets on with it — the same contract as the face gate. Reduced
 * motion never mounts it at all, and `?film=0` skips it for a probe that wants the title without the wait.
 */
const CELL_W = 1600;
const CELL_H = 900;
const CELLS = 12;
const COLS = 6;
/** Through this cell is the build; after it, the city at other hours. Slower first, then brisker. */
const BUILD_LAST = 6;
const BUILD_MS = 520;
const PLATE_MS = 360;
const HOLD_MS = 500;
const GUARD_MS = 8000;

/** The tool's own step names, in its own order — `node tools/make-film.mjs` prints the list to compare. */
const LABELS = [
  "the city's own drawing",
  "the hour — dusk",
  "the flat shapes",
  "+ the ink lines",
  "+ the detail",
  "+ more colours — 12",
  "the plate — with its paper",
  "the marina, at golden hour",
  "the rooftop, at night",
  "palm boulevard, in the neon",
  "the beach, after dark",
  "the marina, at dusk",
];

export function PlateFilm({ onDone }: { onDone: () => void }): ReactElement {
  const ref = useRef<HTMLCanvasElement>(null);
  const done = useRef(false);
  const [step, setStep] = useState(0);
  /**
   * The callback is read through a ref, so a parent that re-renders — the title's own state changes, a font
   * landing — cannot restart the film by handing this effect a new function identity.
   */
  const finish = useRef(onDone);
  finish.current = onDone;

  useEffect(() => {
    let live = true;
    let timer = 0;
    let frame = 0;

    const call = (): void => {
      if (done.current) return;
      done.current = true;
      finish.current();
    };

    // The entry must never wait on this image: a slow network gets the title, not a stuck sheet.
    const guard = window.setTimeout(call, GUARD_MS);

    const sprite = new Image();
    sprite.decoding = "async";
    sprite.src = `${import.meta.env.BASE_URL}film/plate-film.jpg`;
    sprite.onerror = (): void => {
      window.clearTimeout(guard);
      call();
    };
    sprite.onload = (): void => {
      window.clearTimeout(guard);
      if (!live) return;
      const canvas = ref.current;
      const ctx = canvas?.getContext("2d");
      if (!canvas || !ctx) {
        call();
        return;
      }

      // One to one, on purpose. The cells are 1600×900 — the width of a laptop screen — so drawing them at
      // device resolution would *upscale* the source on a retina display and soften exactly the ink lines the
      // build is there to show. The film is drawn at 1:1 with the cell, and the cover-fit's own sub-pixel
      // scaling is smoothed at the best quality the canvas has.
      const cw = Math.max(320, Math.round(canvas.clientWidth || 1280));
      const ch = Math.max(180, Math.round(canvas.clientHeight || 720));
      canvas.width = cw;
      canvas.height = ch;
      ctx.imageSmoothingEnabled = true;
      ctx.imageSmoothingQuality = "high";

      const cover = (into: CanvasRenderingContext2D, index: number): void => {
        const sx = (index % COLS) * CELL_W;
        const sy = Math.floor(index / COLS) * CELL_H;
        const fit = Math.max(cw / CELL_W, ch / CELL_H);
        const dw = CELL_W * fit;
        const dh = CELL_H * fit;
        into.drawImage(sprite, sx, sy, CELL_W, CELL_H, (cw - dw) / 2, (ch - dh) / 2, dw, dh);
      };

      // The previous frame is held offscreen so each step dissolves into the next rather than cutting to it.
      const back = document.createElement("canvas");
      back.width = cw;
      back.height = ch;
      const backCtx = back.getContext("2d");

      let index = 0;
      cover(ctx, 0);
      canvas.dataset.cell = "0";

      const stepFrame = (): void => {
        if (!live) return;
        if (index >= CELLS - 1) {
          timer = window.setTimeout(call, HOLD_MS);
          return;
        }
        const next = index + 1;
        const total = next <= BUILD_LAST ? BUILD_MS : PLATE_MS;
        const fade = Math.round(total * 0.62);
        backCtx?.clearRect(0, 0, cw, ch);
        if (backCtx) cover(backCtx, index);
        const started = performance.now();
        const dissolve = (now: number): void => {
          if (!live) return;
          const t = Math.min(1, (now - started) / fade);
          ctx.clearRect(0, 0, cw, ch);
          if (backCtx) ctx.drawImage(back, 0, 0);
          ctx.globalAlpha = t;
          cover(ctx, next);
          ctx.globalAlpha = 1;
          if (t < 1) {
            frame = requestAnimationFrame(dissolve);
            return;
          }
          canvas.dataset.cell = String(next);
          setStep(next);
          index = next;
          timer = window.setTimeout(stepFrame, Math.max(16, total - fade));
        };
        frame = requestAnimationFrame(dissolve);
      };
      timer = window.setTimeout(stepFrame, HOLD_MS);
    };

    return () => {
      live = false;
      window.clearTimeout(guard);
      window.clearTimeout(timer);
      cancelAnimationFrame(frame);
    };
  }, []);

  return (
    <figure className="entry-film-wrap" aria-hidden="true">
      <canvas ref={ref} className="entry-film" data-testid="entry-film" />
      <figcaption>
        <span className="entry-film-label">{LABELS[step] ?? ""}</span>
        <span className="entry-film-step">
          {String(step + 1).padStart(2, "0")} / {CELLS}
        </span>
      </figcaption>
    </figure>
  );
}