import { useEffect, useRef, type ReactElement } from "react";

/**
 * The film on the title sheet: the press at work.
 *
 * Eighteen cells of one sprite, drawn in order — the photograph as it arrived, the two layers the press reads
 * and cuts, the same canvas flattened at rising colour counts, and then the nine plates the gallery ships in a
 * fast flip. The frames were generated by `tools/make-film.mjs`, which drives *this app's own press*, so what
 * the visitor watches is the pipeline rather than a picture of it.
 *
 * It cannot hold the entry hostage. If the sprite does not arrive within `GUARD_MS`, or fails, or the canvas
 * is unavailable, `onDone` fires and the title gets on with it — the same contract as the face gate. Reduced
 * motion never mounts it at all, and `?film=0` skips it for a probe that wants the title without the wait.
 */
const CELL_W = 576;
const CELL_H = 324;
const CELLS = 18;
const COLS = 6;
/** Cells 0–8 are the redraw; 9–17 are the plate flip. The redraw gets the slower beat. */
const REDRAW_MS = 105;
const FLIP_MS = 72;
const GUARD_MS = 2600;

export function PlateFilm({ onDone }: { onDone: () => void }): ReactElement {
  const ref = useRef<HTMLCanvasElement>(null);
  const done = useRef(false);
  /**
   * The callback is read through a ref, so a parent that re-renders — the title's own state changes, a font
   * landing — cannot restart the film by handing this effect a new function identity.
   */
  const finish = useRef(onDone);
  finish.current = onDone;

  useEffect(() => {
    let live = true;
    let timer = 0;

    const call = (): void => {
      if (done.current) return;
      done.current = true;
      finish.current();
    };

    // The entry must never wait on this image: a slow network gets the title, not a stuck sheet.
    const guard = window.setTimeout(call, GUARD_MS);

    const sprite = new Image();
    sprite.decoding = "async";
    sprite.src = `${import.meta.env.BASE_URL}film/plate-film.jpg`;
    sprite.onerror = (): void => {
      window.clearTimeout(guard);
      call();
    };
    sprite.onload = (): void => {
      window.clearTimeout(guard);
      if (!live) return;
      const canvas = ref.current;
      const ctx = canvas?.getContext("2d");
      if (!canvas || !ctx) {
        call();
        return;
      }
      // Draw at device resolution (capped at 2), the same rule the vapour follows: dust and film both get
      // sharp on a retina screen and neither doubles the cost on a 3× one.
      const scale = Math.min(2, window.devicePixelRatio || 1);
      canvas.width = CELL_W * scale;
      canvas.height = CELL_H * scale;

      let index = 0;
      const next = (): void => {
        if (!live) return;
        if (index >= CELLS) {
          // Hold the last plate a beat, so the flip is a sequence rather than a blur into the title.
          timer = window.setTimeout(call, 170);
          return;
        }
        const sx = (index % COLS) * CELL_W;
        const sy = Math.floor(index / COLS) * CELL_H;
        ctx.drawImage(sprite, sx, sy, CELL_W, CELL_H, 0, 0, canvas.width, canvas.height);
        canvas.dataset.cell = String(index);
        index += 1;
        const delay = index <= CELLS - 9 ? REDRAW_MS : FLIP_MS;
        timer = window.setTimeout(next, delay);
      };
      next();
    };

    return () => {
      live = false;
      window.clearTimeout(guard);
      window.clearTimeout(timer);
    };
  }, [onDone]);

  return (
    <figure className="entry-film-wrap" aria-hidden="true">
      <canvas ref={ref} className="entry-film" data-testid="entry-film" />
      <figcaption>the press, at work</figcaption>
    </figure>
  );
}