import { useCallback, useEffect, useRef, useState, type MouseEvent as ReactMouseEvent } from "react";
import { motion, useReducedMotion } from "motion/react";
import { EditorSurface, type ToolGating } from "./components/EditorSurface";
import { Launch } from "./components/Launch";
import { PlateGate, type PrintChoice } from "./components/PlateGate";
import { PhotoDrop } from "./components/PhotoDrop";
import { PrintDesk } from "./components/PrintDesk";
import { loadImage } from "./world/compose";
import { LOOKS } from "./look/stylise";
import { portraitFromImage, type PortraitResult } from "./look/portrait";
import { SCENES, SCENE_IDS, type SceneId } from "./look/scenes";
import { BeforeAfter } from "./components/BeforeAfter";
import { Fx, Marquee } from "./components/Fx";
import { Hero3D } from "./components/Hero3D";
import { SceneThumb } from "./components/SceneThumb";
import "./type.css";
import type { PlateSource } from "./lib/plates/plates";
import { deskRoot, printChoices } from "./lib/printdesk/client";

/**
 * FIRST EDITION — the city's media machine.
 *
 * The shell follows the studio-site language measured in src/index.css: near-black canvas, deep
 * gradient panels, one gold accent, Art Deco display caps over a grotesque text face, and motion that
 * reveals rather than performs. Each stage is a surface, and each surface exposes a different tool set
 * in the editor — that gating is the level design (docs/editor-contract.md).
 */

const TITLE_GATING: ToolGating = { crop: true, resize: true, frame: true, text: true, filter: false, draw: false, shapes: false, stickers: false };
const PAGE_GATING: ToolGating = { crop: true, resize: true, filter: true, text: true, frame: false, draw: false, shapes: false, stickers: false };
const POSTER_GATING: ToolGating = { crop: true, resize: true, filter: true, text: true, frame: true, draw: true, shapes: true, stickers: true };

/** Which editor surface a printed style leads into, and what that surface asks for. */
const PLANS: Record<string, { surfaceId: string; title: string; brief: string; gating: ToolGating }> = {
  debut: { surfaceId: "loading", title: "the loading screen", brief: "clean grade, face centred, name plate clear", gating: TITLE_GATING },
  loadingscreen: { surfaceId: "loading", title: "the loading screen", brief: "painted panel — put your name in the clear band along the bottom", gating: TITLE_GATING },
  frontpage: { surfaceId: "frontpage", title: "the front page", brief: "face above the fold, masthead clear, tabloid drama", gating: PAGE_GATING },
  poster: { surfaceId: "poster", title: "the VIP poster", brief: "sell the room; you are the night's draw", gating: POSTER_GATING },
};

type Stage = "gate" | "converting" | "printed" | "printing" | "editing" | "city";

const { locations } = printChoices();

/** The city's own plates — generated by tools/print-desk/scenery.mjs, scenery only, never a person. */
const CITY_ART = {
  boulevard: `${import.meta.env.BASE_URL}art/city/boulevard.jpg`,
  marina: `${import.meta.env.BASE_URL}art/city/marina.jpg`,
  downtown: `${import.meta.env.BASE_URL}art/city/downtown.jpg`,
};

const reveal = { hidden: { opacity: 0, y: 18 }, shown: { opacity: 1, y: 0 } };
const EASE = [0.22, 1, 0.36, 1] as const;

export function App() {
  const [stage, setStage] = useState<Stage>("gate");
  const [pendingPhoto, setPendingPhoto] = useState<File | null>(null);
  const [choice, setChoice] = useState<PrintChoice>({ surface: "debut", quality: false });
  const [plate, setPlate] = useState<PlateSource | null>(null);
  const [meta, setMeta] = useState<{ register: string; location: string | null; seed: number } | null>(null);
  const [saved, setSaved] = useState<string | null>(null);
  /** The visitor's own photo, kept only so the plate can be shown against it. */
  const [source, setSource] = useState<string | null>(null);
  /** Which of the city's looks the press prints with. */
  const [look, setLook] = useState("dusk");
  /** Which place in the city the frame is set in. */
  const [scene, setScene] = useState<SceneId>("beach");
  /** The stages the press has actually reached, so the progress line is never a lie. */
  const [stages, setStages] = useState<string[]>([]);
  /** What the cut found, reported honestly under the frame. */
  const [cut, setCut] = useState<Pick<PortraitResult, "cutOut" | "share" | "scene" | "cutSource" | "width"> | null>(null);
  const reduce = useReducedMotion();

  /** Where the city was entered from, so "back" goes where the visitor actually came from. */
  const [viaEditor, setViaEditor] = useState(false);
  /** Fast, or fine for a slower render with truer colour. */
  const [quality, setQuality] = useState<"fast" | "fine">("fast");
  /** A press that could not read the photo reports itself here, where the photo was chosen. */
  const [pressError, setPressError] = useState<string | null>(null);
  /** And so does a drop or a paste that carried no photo, or more than one. */
  const [intakeProblem, setIntakeProblem] = useState<string | null>(null);

  const onSaved = useCallback((dataUrl: string) => {
    setSaved(dataUrl);
    setViaEditor(true);
    setStage("city");
  }, []);
  const image = plate ? (plate.kind === "photo" ? plate.objectUrl : plate.src) : null;
  /** The download's own filename: from the photo's name where there is one, without any text burned in. */
  const frameName = `bahia-rosa-${
    plate && "name" in plate && plate.name ? String(plate.name).replace(/\.[^.]+$/, "") : "frame"
  }.png`;
  const plan = PLANS[choice.surface] ?? PLANS.debut;

  const printed = useCallback(
    (next: PlateSource, printedMeta: { register: string; location: string | null; seed: number }) => {
      setPlate(next);
      setMeta(printedMeta);
      // The plate goes to the fork, not straight into the editor: download it raw, or take it in and
      // make something. The visitor chooses, both are one click.
      setStage("printed");
    },
    [],
  );

  /**
   * The default press: the city's look, in this browser, with no model and nothing uploaded. A photo
   * becomes flat paint with ink over it in a second or two on a phone, which is what makes the
   * platform work for everyone — the desk (a real diffusion model on a GPU) stays as the upgrade.
   */
  const press = useCallback(
    async (file: File) => {
      // Capture the run: if the visitor leaves before this finishes, the result is dropped.
      const token = runToken.current;
      setStages([]);
      setPressError(null);
      setStage("converting");
      const url = URL.createObjectURL(file);
      try {
        const image = await loadImage(url);
        const preset = LOOKS[look]?.options ?? LOOKS.dusk.options;
        const result = await portraitFromImage(image, {
          ...preset,
          scene,
          look,
          fine: quality === "fine",
          seed: 1 + (file.size % 997),
          onStage: (label) => setStages((seen) => (seen.includes(label) ? seen : [...seen, label])),
        });
        if (token !== runToken.current) {
          URL.revokeObjectURL(url);
          return;
        }
        setCut({
          cutOut: result.cutOut,
          share: result.share,
          scene: result.scene,
          cutSource: result.cutSource,
          width: result.width,
        });
        setPlate({ kind: "photo", objectUrl: result.canvas.toDataURL("image/jpeg", 0.94), name: file.name });
        setSource(url); // kept for the before/after comparison; revoked on reset
        setMeta(null);
        setStage("printed");
      } catch (failure) {
        if (token !== runToken.current) {
          URL.revokeObjectURL(url);
          return;
        }
        // A failure here used to send the visitor to the desk screen — ComfyUI on a machine that does not
        // exist for anyone on the deployed site — which is how a group photo ended up staring at "no
        // print desk is running". The desk is an opt-in this page was pointed at: with none, the press
        // reports itself where the photo was chosen, with the reason attached.
        URL.revokeObjectURL(url);
        if (deskRoot()) {
          setPendingPhoto(file);
          setStage("printing");
          return;
        }
        setPressError(failure instanceof Error ? failure.message : "the press could not read that photo");
        setStage("gate");
      }
    },
    [scene, look, quality],
  );

  /**
   * One door for every way a photograph arrives: the picker, a drop anywhere on the page, a paste.
   *
   * Three entrances and one behaviour, because the alternative is three subtly different behaviours —
   * which is how a paste ends up not saving the payoff that a click does.
   */
  const takePhoto = useCallback(
    (file: File) => {
      setIntakeProblem(null);
      setPressError(null);
      // The press decides the print: the desk keeps its own defaults, and the visitor's only choices are
      // the place and the hour, which live on the sections above.
      setChoice({ surface: "debut", quality: false });
      if (deskRoot()) {
        // This page was pointed at a desk on purpose (?desk=…), so print there, with the model.
        setPendingPhoto(file);
        setStage("printing");
        return;
      }
      void press(file);
    },
    [press],
  );

  const useFallback = useCallback(() => {
    // The payoff stage needs an artwork and the deployed build has no GPU: the city's own plate is
    // the honest stand-in — scenery, no person, nothing borrowed.
    setSaved(CITY_ART.marina);
    setMeta(null);
    setViaEditor(false);
    setStage("city");
  }, []);

  /**
   * Back to the start, from anywhere — including *during* a press.
   *
   * Two things this has to get right, and did not:
   *
   *   1. A press still running must not land after the visitor has walked away. The press carries this
   *      token; the reset bumps it, and a result from an older token is dropped instead of pulling them
   *      forward into a stage they left.
   *   2. The intake does not exist at click time — the gate stage renders it — so the browser has
   *      nothing to scroll to when it follows `#intake`, and the first click did nothing at all. The
   *      scroll happens here instead, after React has rendered the stage.
   */
  const runToken = useRef(0);
  const reset = useCallback(() => {
    runToken.current += 1;
    setPlate(null);
    setPendingPhoto(null);
    setSaved(null);
    setMeta(null);
    setStage("gate");
    if (source) URL.revokeObjectURL(source);
    setSource(null);
    window.setTimeout(() => {
      const node = document.getElementById("intake");
      if (!node) return;
      node.scrollIntoView({ behavior: reduce ? "auto" : "smooth", block: "start" });
      node.focus({ preventScroll: true });
    }, 0);
  }, [source, reduce]);
  // ?demo=launch — the tour without the model. The deployed build has no GPU, so a visitor (or a
  // judge) who cannot run the desk still gets to see the payoff: the city's own plate, launched into
  // the city. Same components, same exporter; only the artwork's provenance changes.
  useEffect(() => {
    const demo = new URLSearchParams(window.location.search).get("demo");
    if (demo === "launch") {
      useFallback();
      return;
    }
    // The editor without a GPU: the city's own plate stands in as the artwork, so the React Image
    // Editor surface (and its gating) can be seen, driven and tested on any machine.
    if (demo === "editor") {
      setPlate({ kind: "plate", id: "city-downtown", src: CITY_ART.downtown });
      setMeta(null);
      setStage("editing");
    }
  }, [useFallback]);

  // Two steps, because that is what the product is: you get a plate, and the city runs it. The
  // editor is a detour inside the first step, not a stage of its own — which is why the payoff can be
  // reached without it.
  const stepIndex = stage === "city" ? 1 : 0;
  const steps = [
    { label: "Your plate", hint: "a photo, and what the city makes of it" },
    { label: "The city", hint: "billboard · foyer · feed · postcard" },
  ];

  // A stage that changes silently leaves a keyboard or screen-reader visitor at the top of the page with
  // no idea anything happened. Move the view to the work, and put focus there, so tabbing continues from
  // where the new thing is.
  useEffect(() => {
    if (stage === "gate") return;
    const node = document.getElementById("stage");
    if (!node) return;
    node.scrollIntoView({ behavior: reduce ? "auto" : "smooth", block: "start" });
    node.focus({ preventScroll: true });
  }, [stage, reduce]);

  /**
   * One way home, from every place that offers it.
   *
   * The hero's own "Bring a photo" was a bare `#intake` anchor, and the intake only exists once the
   * gate stage renders it — so on any other stage the click had nothing to scroll to and did nothing.
   * Every route home now goes through here: prevent the hash jump, reset, then scroll once React has
   * rendered the stage. The href stays on the elements for the keyboard and for a copied link.
   */
  const goHome = useCallback(
    (event: ReactMouseEvent) => {
      event.preventDefault();
      reset();
    },
    [reset],
  );

  /** What the finish actually produced — read from the result, so it cannot be a claim. */
  const cutLabel = `${quality === "fine" ? "fine" : "fast"} · ${cut?.width ?? 0}px wide`;

  /** What the cut did, and what the finish produced — reported from the result, never guessed at. */
  const cutLine =
    (cut?.cutSource === "model"
      ? `found you in the frame — ${Math.round(cut.share * 100)}% of it`
      : cut?.cutSource === "classic"
        ? "the rough find did the cut — the segmenter could not load"
        : meta
          ? "printed at the desk"
          : cut
            ? "no person could be told apart, so the whole frame was painted"
            : "") + (cut ? ` · ${cutLabel}` : "");

  return (
    <div className="grain vignette min-h-screen">
      <Fx />
      <a href="#intake" className="skip">
        Skip to the press
      </a>

      <header className="masthead rule sticky top-0 z-20 border-b">
        <div className="mx-auto max-w-[1280px] px-8">
          <div className="flex flex-wrap items-baseline justify-between gap-x-6 gap-y-2 py-4">
            <div className="flex items-baseline gap-4">
              <a
                href="#intake"
                data-testid="home"
                onClick={goHome}
                className="wordmark text-3xl leading-none"
                aria-label="Bahía Rosa — back to the start"
              >
                Bahía Rosa
              </a>
              <span className="kicker hidden sm:inline">la gaviota · the coast edition</span>
            </div>
            <div className="flex items-center gap-6">
              <a
                href="#intake"
                data-testid="bring-a-photo"
                onClick={goHome}
                className="fx-link text-xs"
                style={{ color: "var(--color-muted)" }}
              >
                bring a photo
              </a>
              <span className="kicker hidden md:inline">{locations.length} places</span>
              <span className="kicker" style={{ color: "var(--color-flag)" }}>
                {deskRoot() ? "printing at the desk" : "printing in your browser"}
              </span>
            </div>
          </div>
          <div className="nameplate-rule" aria-hidden="true" />
          <nav className="steprail py-3" aria-label="The run">
            {steps.map((step, index) => (
              <span
                key={step.label}
                className="step"
                data-state={index === stepIndex ? "now" : index < stepIndex ? "done" : "todo"}
                aria-current={index === stepIndex ? "step" : undefined}
              >
                {index > 0 ? <span style={{ color: "var(--color-faint)" }}>·</span> : null}
                {step.label.toLowerCase()}
              </span>
            ))}
          </nav>
        </div>
      </header>

      {/* A photo from anywhere: dropped on the page, or pasted. Live where a new photo means something. */}
      <PhotoDrop
        enabled={stage === "gate" || stage === "printed"}
        onPhoto={takePhoto}
        onProblem={setIntakeProblem}
      />

      <main className="mx-auto max-w-[1280px] px-8">
        <motion.section
          initial={reduce ? undefined : "hidden"}
          animate={reduce ? undefined : "shown"}
          variants={reveal}
          transition={{ duration: 0.7, ease: EASE }}
          data-testid="hero"
          className="rule relative mt-8 overflow-hidden border"
        >
          <Hero3D scene={scene} look={look} className="absolute inset-0 h-full w-full" />
          <div className="city-scrim" aria-hidden="true" />
          <div className="relative px-10 py-20">
            <h1 className="display mt-5 text-5xl">Bahía Rosa</h1>
            <p className="deck mt-7">One photo. The city paints it, then runs it.</p>

            <div className="mt-9 flex flex-wrap items-center gap-3">
              <a
                href="#intake"
                data-testid="hero-cta"
                onClick={goHome}
                className="lift border px-6 py-3 text-xs tracking-[0.2em] uppercase"
                style={{ background: "var(--color-gold)", color: "var(--color-ink)", borderColor: "var(--color-gold)" }}
              >
                Bring a photo
              </a>
              <span className="text-xs" style={{ color: "var(--color-faint)" }}>
                no account · no upload
              </span>
            </div>

            </div>
        </motion.section>

        <div className="mt-8">
          <Marquee items={locations.map((place) => place.label)} />
        </div>

        {stage === "gate" ? (
          <motion.div
            initial={reduce ? undefined : "hidden"}
            whileInView={reduce ? undefined : "shown"}
            viewport={{ once: true, margin: "-80px" }}
            variants={reveal}
            transition={{ duration: 0.6, ease: EASE }}
            id="intake"
            style={{ scrollMarginTop: "7.5rem" }}
            className="mt-10"
          >
            <section className="section-tight" aria-labelledby="hour-heading">
              <h2 id="hour-heading" className="display" style={{ color: "var(--color-paper)" }}>
                <span style={{ color: "var(--color-faint)" }}>~ </span>the hour
              </h2>
              <p className="measure mt-2 text-xs" style={{ color: "var(--color-muted)" }}>
                {LOOKS[look]?.blurb ?? ""} The hour grades the place — its sky, its water, its asphalt —
                not only the person standing in it.
              </p>
              <div className="mt-4 flex flex-wrap gap-3" role="group" aria-label="The hour">
                {Object.entries(LOOKS).map(([id, preset]) => {
                  const active = id === look;
                  return (
                    <button
                      key={id}
                      type="button"
                      data-testid={`look-${id}`}
                      aria-pressed={active}
                      onClick={() => setLook(id)}
                      className="lift text-left"
                      style={{ border: `1px solid ${active ? "var(--color-accent)" : "var(--color-rule)"}` }}
                    >
                      <SceneThumb scene={scene} look={id} className="w-[208px]" />
                      <span
                        className="block px-3 py-2 text-xs"
                        style={{ color: active ? "var(--color-accent)" : "var(--color-muted)" }}
                      >
                        {preset.label.toLowerCase()}
                        {active ? " · chosen" : ""}
                      </span>
                    </button>
                  );
                })}
              </div>
            </section>
            <section className="section-tight" aria-labelledby="place-heading">
              <h2 id="place-heading" className="display" style={{ color: "var(--color-paper)" }}>
                <span style={{ color: "var(--color-faint)" }}>~ </span>the place
              </h2>
              <p className="measure mt-2 text-xs" style={{ color: "var(--color-muted)" }}>
                {SCENES[scene].blurb}. Shown at the hour you picked, because that is what the press
                will print.
              </p>
              <div className="mt-4 flex flex-wrap gap-3" role="group" aria-label="The place">
                {SCENE_IDS.map((id) => {
                  const active = id === scene;
                  return (
                    <button
                      key={id}
                      type="button"
                      data-testid={`scene-${id}`}
                      aria-pressed={active}
                      onClick={() => setScene(id)}
                      className="lift text-left"
                      style={{ border: `1px solid ${active ? "var(--color-accent)" : "var(--color-rule)"}` }}
                    >
                      <SceneThumb scene={id} look={look} className="w-[208px]" />
                      <span
                        className="block px-3 py-2 text-xs"
                        style={{ color: active ? "var(--color-accent)" : "var(--color-muted)" }}
                      >
                        {SCENES[id].label.toLowerCase()}
                        {active ? " · chosen" : ""}
                      </span>
                    </button>
                  );
                })}
              </div>
            </section>
            <section className="section-tight" aria-labelledby="finish-heading">
              <h2 id="finish-heading" className="display" style={{ color: "var(--color-paper)" }}>
                <span style={{ color: "var(--color-faint)" }}>~ </span>the finish
              </h2>
              <p className="measure mt-2 text-xs" id="finish-note" style={{ color: "var(--color-muted)" }}>
                fast: seconds. fine: bigger, truer colour, slower.
              </p>
              <div
                className="mt-4 flex flex-wrap gap-3"
                role="radiogroup"
                aria-labelledby="finish-heading"
                aria-describedby="finish-note"
              >
                {(
                  [
                    ["fast", "fast", "a few seconds"],
                    ["fine", "fine", "slower, truer colour, bigger"],
                  ] as const
                ).map(([id, label, hint]) => (
                  <button
                    key={id}
                    type="button"
                    role="radio"
                    data-testid={`finish-${id}`}
                    aria-checked={quality === id}
                    onClick={() => setQuality(id)}
                    className="lift text-left"
                    style={{
                      border: `1px solid ${quality === id ? "var(--color-accent)" : "var(--color-rule)"}`,
                      padding: "10px 14px",
                    }}
                  >
                    <span
                      className="block text-xs"
                      style={{ color: quality === id ? "var(--color-accent)" : "var(--color-paper)" }}
                    >
                      {label}
                      {quality === id ? " · chosen" : ""}
                    </span>
                    <span className="block text-xs" style={{ color: "var(--color-faint)" }}>
                      {hint}
                    </span>
                  </button>
                ))}
              </div>
            </section>
            {pressError ? (
              <p
                data-testid="press-error"
                role="status"
                className="measure mt-6 text-xs"
                style={{ color: "var(--color-danger)" }}
              >
                that photo could not be pressed — {pressError}. another one, or a smaller file, will work.
              </p>
            ) : null}
            {intakeProblem ? (
              <p
                data-testid="intake-problem"
                role="status"
                className="measure mt-3 text-xs"
                style={{ color: "var(--color-danger)" }}
              >
                {intakeProblem}
              </p>
            ) : null}
            <PlateGate onPhoto={takePhoto} />
          </motion.div>
        ) : null}

        <div id="stage" tabIndex={-1} style={{ scrollMarginTop: "7.5rem" }} className="outline-none">
        <p className="sr-only" role="status" data-testid="stage-status">
          step {stepIndex + 1} of {steps.length}: {steps[stepIndex].label}
        </p>

        {stage === "converting" ? (
          <motion.section
            initial={reduce ? undefined : "hidden"}
            animate={reduce ? undefined : "shown"}
            variants={reveal}
            transition={{ duration: 0.5, ease: EASE }}
            className="panel rule mt-10 border p-8"
            data-testid="converting"
          >
            <p className="kicker">Step 1 · The press</p>
            <h2 className="display mt-3 text-4xl">Printing you into the city</h2>
            <p className="mt-3 max-w-[62ch] text-sm leading-relaxed text-[color:var(--color-muted)]">
              Everything below happens inside this page. Your photo is not uploaded anywhere, and there
              is no key or account in the path.
            </p>
            <ol className="mt-6 space-y-2" aria-live="polite">
              {stages.map((label) => (
                <li key={label} className="flex items-baseline gap-3 text-sm text-[color:var(--color-body)]">
                  <span style={{ color: "var(--color-gold)" }}>✓</span>
                  {label}
                </li>
              ))}
            </ol>
            <div className="rule mt-6 h-[3px] w-full overflow-hidden border" aria-hidden="true">
              <motion.div
                className="h-full"
                style={{ background: "var(--color-gold)" }}
                initial={{ width: "6%" }}
                animate={{ width: `${Math.min(94, 18 + stages.length * 19)}%` }}
                transition={{ duration: 0.45, ease: EASE }}
              />
            </div>
          </motion.section>
        ) : null}

        {stage === "printed" && image ? (
          <motion.section
            initial={reduce ? undefined : { opacity: 0, y: 14 }}
            animate={reduce ? undefined : { opacity: 1, y: 0 }}
            transition={{ duration: 0.5, ease: EASE }}
            className="panel rule mt-10 border p-8"
            data-testid="printed-fork"
          >
            <h2 className="display mt-3 text-4xl">
              There you are, in {SCENES[cut?.scene ?? scene].label.toLowerCase()}
            </h2>
            <p className="measure mt-3 text-xs" style={{ color: "var(--color-muted)" }} data-testid="cut-line">
              {cutLine}
            </p>

            <div className="mt-7 grid gap-7 lg:grid-cols-[minmax(0,1fr)_320px]">
              <div className="rule overflow-hidden border">
                <img
                  src={image}
                  alt="Your plate, freshly printed"
                  data-testid="printed-plate"
                  className="w-full"
                />
              </div>
              <div className="flex flex-col gap-3">
                <a href={image} download={frameName} data-testid="download-raw" className="btn text-center">
                  Download it raw
                </a>
                <span className="text-xs" style={{ color: "var(--color-faint)" }}>
                  clean PNG · no text, no watermark
                </span>
                <button
                  type="button"
                  data-testid="take-to-city"
                  onClick={() => {
                    setSaved(image);
                    setViaEditor(false);
                    setStage("city");
                  }}
                  className="btn-quiet text-center"
                >
                  Take it into the city
                </button>
                <span className="text-xs" style={{ color: "var(--color-faint)" }}>
                  the billboard · the foyer · the feed · the postcard — straight there, no editing needed
                </span>
                <button
                  type="button"
                  data-testid="edit-in-editor"
                  onClick={() => setStage("editing")}
                  className="btn-quiet text-center"
                >
                  Open the editor instead
                </button>
                <span className="text-xs" style={{ color: "var(--color-faint)" }}>
                  text · filters · crop · drawing · shapes · stickers
                </span>
                <button
                  type="button"
                  onClick={reset}
                  className="fx-link mt-3 text-left text-xs tracking-[0.2em] text-[color:var(--color-faint)] uppercase hover:text-[color:var(--color-gold)]"
                >
                  Bring a different photo
                </button>
              </div>
            </div>

            {source && image ? (
              <div className="mt-7">
                <BeforeAfter before={source} after={image} />
              </div>
            ) : null}
          </motion.section>
        ) : null}

        {stage === "printing" && pendingPhoto ? (
          <div className="mt-10">
            <PrintDesk file={pendingPhoto} choice={choice} onPrinted={printed} />
          </div>
        ) : null}

        {stage === "editing" && image ? (
          <motion.section
            initial={reduce ? undefined : { opacity: 0, y: 14 }}
            animate={reduce ? undefined : { opacity: 1, y: 0 }}
            transition={{ duration: 0.5, ease: EASE }}
            className="editor-shell panel rule mt-10 border p-8"
          >
            <div className="rule mb-5 flex items-center justify-between border-b pb-4">
              <div>
                <h2 className="display text-3xl">{plan.title}</h2>
              </div>
              <button
                type="button"
                data-testid="start-over"
                onClick={reset}
                className="lift rule border px-4 py-2 text-xs tracking-[0.2em] text-[color:var(--color-body)] uppercase hover:text-[color:var(--color-gold)]"
              >
                Start over
              </button>
            </div>
            <p className="mb-5 max-w-[62ch] text-sm leading-relaxed text-[color:var(--color-muted)]">
              Brief: {plan.brief}.
              {meta?.location ? <span> Printed at the {meta.location}.</span> : null}
              {plate?.kind === "plate" ? <span> (Using a cast plate.)</span> : null}
            </p>
            {source && image ? <BeforeAfter before={source} after={image} /> : null}
            {image ? (
              <div className="mt-5 flex flex-wrap items-center gap-3">
                <a
                  href={image}
                  download={frameName}
                  data-testid="download-frame"
                  className="lift border px-5 py-3 text-xs tracking-[0.2em] uppercase"
                  style={{ background: "var(--color-gold)", color: "var(--color-ink)", borderColor: "var(--color-gold)" }}
                >
                  Download this frame
                </a>
                <span className="kicker" style={{ color: "var(--color-muted)" }}>
                  clean PNG · no text, no watermark
                </span>
                {cut ? (
                  <span
                    className="kicker"
                    style={{ color: "var(--color-muted)" }}
                    data-testid="cut-source"
                  >
                    {cut.cutSource === "model"
                      ? `found by the segmenter (${Math.round(cut.share * 100)}% of the frame)`
                      : cut.cutSource === "classic"
                        ? "rough find — the segmenter could not load"
                        : "whole frame painted"}
                  </span>
                ) : null}
              </div>
            ) : null}
            <EditorSurface surfaceId={plan.surfaceId} image={image} gating={plan.gating} onSaved={onSaved} />
          </motion.section>
        ) : null}

        {stage === "city" && saved ? (
          <motion.div
            initial={reduce ? undefined : { opacity: 0, y: 14 }}
            animate={reduce ? undefined : { opacity: 1, y: 0 }}
            transition={{ duration: 0.5, ease: EASE }}
            className="mt-10"
          >
            <Launch
              artworkUrl={saved}
              location={meta?.location ?? null}
              onBack={() => setStage(viaEditor ? "editing" : "printed")}
              backLabel={viaEditor ? "Back to the editor" : "Back to your plate"}
            />
          </motion.div>
        ) : null}
        </div>
      </main>

      <footer className="rule mx-auto mt-16 max-w-[1280px] border-t px-8 py-8">
        <p className="kicker">Bahía Rosa · la gaviota</p>
        <p className="mt-3 max-w-[70ch] text-xs leading-relaxed text-[color:var(--color-faint)]">
          Unofficial fan-made project for the Unlayer Build with React Image Editor Challenge. Not
          affiliated with, endorsed by, or connected to Rockstar Games or Take-Two Interactive. All
          visuals are original work; the city (Bahía Rosa), its newspaper (LA GAVIOTA) and every
          placement it publishes into are invented. The print desk runs on your own machine: no
          account, no API key, and nothing you upload leaves it.
        </p>
      </footer>
    </div>
  );
}
