import { useCallback, useEffect, useState } from "react";
import { motion, useReducedMotion } from "motion/react";
import { EditorSurface, type ToolGating } from "./components/EditorSurface";
import { Launch } from "./components/Launch";
import { PlateGate, type PrintChoice } from "./components/PlateGate";
import { PrintDesk } from "./components/PrintDesk";
import { loadImage } from "./world/compose";
import { LOOKS } from "./look/stylise";
import { portraitFromImage, type PortraitResult } from "./look/portrait";
import { SCENES, SCENE_IDS, sceneSrc, type SceneId } from "./look/scenes";
import { BeforeAfter } from "./components/BeforeAfter";
import type { PlateSource } from "./lib/plates/plates";
import { deskRoot, printChoices } from "./lib/printdesk/client";

/**
 * FIRST EDITION — the city's media machine.
 *
 * The shell follows the studio-site language measured in src/index.css: near-black canvas, deep
 * gradient panels, one gold accent, Art Deco display caps over a grotesque text face, and motion that
 * reveals rather than performs. Each stage is a surface, and each surface exposes a different tool set
 * in the editor — that gating is the level design (docs/editor-contract.md).
 */

const TITLE_GATING: ToolGating = { crop: true, resize: true, frame: true, text: true, filter: false, draw: false, shapes: false, stickers: false };
const PAGE_GATING: ToolGating = { crop: true, resize: true, filter: true, text: true, frame: false, draw: false, shapes: false, stickers: false };
const POSTER_GATING: ToolGating = { crop: true, resize: true, filter: true, text: true, frame: true, draw: true, shapes: true, stickers: true };

/** Which editor surface a printed style leads into, and what that surface asks for. */
const PLANS: Record<string, { surfaceId: string; title: string; brief: string; gating: ToolGating }> = {
  debut: { surfaceId: "loading", title: "the loading screen", brief: "clean grade, face centred, name plate clear", gating: TITLE_GATING },
  loadingscreen: { surfaceId: "loading", title: "the loading screen", brief: "painted panel — put your name in the clear band along the bottom", gating: TITLE_GATING },
  frontpage: { surfaceId: "frontpage", title: "the front page", brief: "face above the fold, masthead clear, tabloid drama", gating: PAGE_GATING },
  poster: { surfaceId: "poster", title: "the VIP poster", brief: "sell the room; you are the night's draw", gating: POSTER_GATING },
};

type Stage = "gate" | "converting" | "printing" | "editing" | "launch";

const { locations } = printChoices();

/** The city's own plates — generated by tools/print-desk/scenery.mjs, scenery only, never a person. */
const CITY_ART = {
  boulevard: `${import.meta.env.BASE_URL}art/city/boulevard.jpg`,
  marina: `${import.meta.env.BASE_URL}art/city/marina.jpg`,
  downtown: `${import.meta.env.BASE_URL}art/city/downtown.jpg`,
};

const reveal = { hidden: { opacity: 0, y: 18 }, shown: { opacity: 1, y: 0 } };
const EASE = [0.22, 1, 0.36, 1] as const;

export function App() {
  const [stage, setStage] = useState<Stage>("gate");
  const [pendingPhoto, setPendingPhoto] = useState<File | null>(null);
  const [choice, setChoice] = useState<PrintChoice>({ surface: "debut", quality: false });
  const [plate, setPlate] = useState<PlateSource | null>(null);
  const [meta, setMeta] = useState<{ register: string; location: string | null; seed: number } | null>(null);
  const [saved, setSaved] = useState<string | null>(null);
  /** The visitor's own photo, kept only so the plate can be shown against it. */
  const [source, setSource] = useState<string | null>(null);
  /** Which of the city's looks the press prints with. */
  const [look, setLook] = useState("dusk");
  /** Which place in the city the frame is set in. */
  const [scene, setScene] = useState<SceneId>("beach");
  /** The stages the press has actually reached, so the progress line is never a lie. */
  const [stages, setStages] = useState<string[]>([]);
  /** What the cut found, reported honestly under the frame. */
  const [cut, setCut] = useState<Pick<PortraitResult, "cutOut" | "share" | "scene"> | null>(null);
  const reduce = useReducedMotion();

  const onSaved = useCallback((dataUrl: string) => {
    setSaved(dataUrl);
    setStage("launch");
  }, []);
  const image = plate ? (plate.kind === "photo" ? plate.objectUrl : plate.src) : null;
  /** The download's own filename: from the photo's name where there is one, without any text burned in. */
  const frameName = `late-edition-${
    plate && "name" in plate && plate.name ? String(plate.name).replace(/\.[^.]+$/, "") : "frame"
  }.png`;
  const plan = PLANS[choice.surface] ?? PLANS.debut;

  const printed = useCallback(
    (next: PlateSource, printedMeta: { register: string; location: string | null; seed: number }) => {
      setPlate(next);
      setMeta(printedMeta);
      setStage("editing");
    },
    [],
  );

  /**
   * The default press: the city's look, in this browser, with no model and nothing uploaded. A photo
   * becomes flat paint with ink over it in a second or two on a phone, which is what makes the
   * platform work for everyone — the desk (a real diffusion model on a GPU) stays as the upgrade.
   */
  const press = useCallback(
    async (file: File) => {
      setStages([]);
      setStage("converting");
      const url = URL.createObjectURL(file);
      try {
        const image = await loadImage(url);
        const preset = LOOKS[look]?.options ?? LOOKS.dusk.options;
        const result = await portraitFromImage(image, {
          ...preset,
          scene,
          seed: 1 + (file.size % 997),
          onStage: (label) => setStages((seen) => (seen.includes(label) ? seen : [...seen, label])),
        });
        setCut({ cutOut: result.cutOut, share: result.share, scene: result.scene });
        setPlate({ kind: "photo", objectUrl: result.canvas.toDataURL("image/jpeg", 0.94), name: file.name });
        setSource(url); // kept for the before/after comparison; revoked on reset
        setMeta(null);
        setStage("editing");
      } catch {
        URL.revokeObjectURL(url);
        // A file this browser cannot decode still takes the desk path, which reports the problem.
        setPendingPhoto(file);
        setStage("printing");
      }
    },
    [scene, look],
  );

  const useFallback = useCallback(() => {
    // The payoff stage needs an artwork and the deployed build has no GPU: the city's own plate is
    // the honest stand-in — scenery, no person, nothing borrowed.
    setSaved(CITY_ART.marina);
    setMeta(null);
    setStage("launch");
  }, []);

  const reset = useCallback(() => {
    setPlate(null);
    setPendingPhoto(null);
    setSaved(null);
    setMeta(null);
    setStage("gate");
    if (source) URL.revokeObjectURL(source);
    setSource(null);
  }, [source]);
  // ?demo=launch — the tour without the model. The deployed build has no GPU, so a visitor (or a
  // judge) who cannot run the desk still gets to see the payoff: the city's own plate, launched into
  // the city. Same components, same exporter; only the artwork's provenance changes.
  useEffect(() => {
    const demo = new URLSearchParams(window.location.search).get("demo");
    if (demo === "launch") {
      useFallback();
      return;
    }
    // The editor without a GPU: the city's own plate stands in as the artwork, so the React Image
    // Editor surface (and its gating) can be seen, driven and tested on any machine.
    if (demo === "editor") {
      setPlate({ kind: "plate", id: "city-downtown", src: CITY_ART.downtown });
      setMeta(null);
      setStage("editing");
    }
  }, [useFallback]);

  const stepIndex = stage === "gate" ? 0 : stage === "converting" ? 0 : stage === "printing" || stage === "editing" ? 1 : 2;
  const steps = [
    { label: "The plate", hint: "bring a photo" },
    { label: "The editor", hint: "make it yours" },
    { label: "The city", hint: "run it" },
  ];

  return (
    <div className="grain vignette min-h-screen">
      <a href="#intake" className="skip">
        Skip to the press
      </a>

      <header className="masthead rule sticky top-0 z-20 border-b">
        <div className="mx-auto max-w-[1280px] px-8">
          <div className="flex flex-wrap items-baseline justify-between gap-x-6 gap-y-2 py-4">
            <div className="flex items-baseline gap-4">
              <span className="wordmark text-3xl leading-none">Late Edition</span>
              <span className="kicker hidden sm:inline">Bahía Rosa · La Gaviota</span>
            </div>
            <div className="flex items-center gap-6">
              <span className="kicker hidden md:inline">{locations.length} places</span>
              <span className="kicker" style={{ color: "var(--color-gold)" }}>
                {deskRoot() ? "printing at the desk" : "printing in your browser"}
              </span>
            </div>
          </div>
          <div className="nameplate-rule" aria-hidden="true" />
          <nav className="steprail py-3" aria-label="The run">
            {steps.map((step, index) => (
              <span
                key={step.label}
                className="step"
                data-state={index === stepIndex ? "now" : index < stepIndex ? "done" : "todo"}
                aria-current={index === stepIndex ? "step" : undefined}
              >
                <span className="step-num">{index + 1}</span>
                {step.label}
                <span className="hidden lg:inline" style={{ color: "var(--color-faint)", letterSpacing: "0.12em" }}>
                  {step.hint}
                </span>
              </span>
            ))}
          </nav>
        </div>
      </header>

      <main className="mx-auto max-w-[1280px] px-8">
        <motion.section
          initial={reduce ? undefined : "hidden"}
          animate={reduce ? undefined : "shown"}
          variants={reveal}
          transition={{ duration: 0.7, ease: EASE }}
          data-testid="hero"
          className="rule relative mt-8 overflow-hidden border"
        >
          <img
            src={sceneSrc(scene)}
            alt={`${SCENES[scene].label} — the place your frame is set in`}
            className="absolute inset-0 h-full w-full object-cover"
            aria-hidden="true"
          />
          <div className="city-scrim" aria-hidden="true" />
          <div className="relative px-10 py-20">
            <p className="kicker">The city prints you</p>
            <h1 className="display mt-5 text-6xl sm:text-7xl">Late Edition</h1>
            <p className="deck mt-7">
              Bring one photo. It becomes a painted frame in the city&rsquo;s own light — flat colour,
              ink over the lines, violet in the shadows and gold where the sun lands — then the editor
              turns it into tonight&rsquo;s poster and{" "}
              <strong>the city runs it: the billboard, the venue display, the feed, the postcard home</strong>.
            </p>

            <div className="mt-9 flex flex-wrap items-center gap-3">
              <a
                href="#intake"
                data-testid="hero-cta"
                className="lift border px-6 py-3 text-xs tracking-[0.2em] uppercase"
                style={{ background: "var(--color-gold)", color: "var(--color-ink)", borderColor: "var(--color-gold)" }}
              >
                Bring a photo
              </a>
              <a
                href="?demo=launch"
                className="lift rule border px-6 py-3 text-xs tracking-[0.2em] text-[color:var(--color-paper)] uppercase"
              >
                See the payoff first
              </a>
              <span className="kicker" style={{ color: "var(--color-muted)" }}>
                no account · no upload · nothing leaves the page
              </span>
            </div>

            <div className="stat-row mt-12">
              {[
                { value: "1.3s", label: "a plate, in the browser" },
                { value: "4", label: "surfaces it lands on" },
                { value: "0", label: "keys, accounts, uploads" },
                { value: String(locations.length), label: "places in the city" },
              ].map((stat) => (
                <div key={stat.label} className="stat">
                  <div className="stat-value">{stat.value}</div>
                  <div className="stat-label">{stat.label}</div>
                </div>
              ))}
            </div>
          </div>
        </motion.section>

        <div className="rule mt-8 overflow-hidden border-y py-3">
          <div className="ticker kicker">
            {[...locations, ...locations].map((place, index) => (
              <span key={`${place.id}-${index}`} className="mx-6">
                {place.label} <span style={{ color: "var(--color-gold)" }}>·</span>
              </span>
            ))}
          </div>
        </div>

        {stage === "gate" ? (
          <motion.div
            initial={reduce ? undefined : "hidden"}
            whileInView={reduce ? undefined : "shown"}
            viewport={{ once: true, margin: "-80px" }}
            variants={reveal}
            transition={{ duration: 0.6, ease: EASE }}
            id="intake"
            style={{ scrollMarginTop: "7.5rem" }}
            className="mt-10"
          >
            <div className="panel rule mb-6 border p-6">
              <div className="flex flex-wrap items-baseline justify-between gap-4">
                <div>
                  <span className="kicker">The look</span>
                  <p className="mt-2 text-sm text-[color:var(--color-muted)]">
                    {LOOKS[look]?.blurb ?? ""}
                  </p>
                </div>
                <div className="flex flex-wrap gap-2" role="group" aria-label="The look">
                  {Object.entries(LOOKS).map(([id, preset]) => {
                    const active = id === look;
                    return (
                      <button
                        key={id}
                        type="button"
                        data-testid={`look-${id}`}
                        aria-pressed={active}
                        onClick={() => setLook(id)}
                        className="lift rule border px-4 py-2 text-xs tracking-[0.2em] uppercase"
                        style={{
                          color: active ? "var(--color-ink)" : "var(--color-muted)",
                          background: active ? "var(--color-gold)" : "transparent",
                          borderColor: active ? "var(--color-gold)" : undefined,
                        }}
                      >
                        {preset.label}
                      </button>
                    );
                  })}
                </div>
              </div>
            </div>
            <div className="panel rule mb-6 border p-6">
              <div className="flex flex-wrap items-baseline justify-between gap-4">
                <div>
                  <span className="kicker">Where you&rsquo;ll be</span>
                  <p className="mt-2 text-sm text-[color:var(--color-muted)]">{SCENES[scene].blurb}</p>
                </div>
              </div>
              <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3" role="group" aria-label="Where you'll be">
                {SCENE_IDS.map((id) => {
                  const active = id === scene;
                  return (
                    <button
                      key={id}
                      type="button"
                      data-testid={`scene-${id}`}
                      aria-pressed={active}
                      onClick={() => setScene(id)}
                      className="lift rule overflow-hidden border text-left"
                      style={{ borderColor: active ? "var(--color-gold)" : undefined }}
                    >
                      <img
                        src={sceneSrc(id)}
                        alt=""
                        className="h-32 w-full object-cover"
                        style={{ opacity: active ? 1 : 0.72 }}
                      />
                      <span className="flex items-baseline justify-between gap-2 px-3 py-3">
                        <span
                          className="text-sm"
                          style={{ color: active ? "var(--color-gold)" : "var(--color-body)" }}
                        >
                          {SCENES[id].label}
                        </span>
                        {active ? <span className="kicker" style={{ color: "var(--color-gold)" }}>chosen</span> : null}
                      </span>
                    </button>
                  );
                })}
              </div>
            </div>
            <PlateGate
              onPhoto={(file, picked) => {
                setChoice(picked);
                if (deskRoot()) {
                  // This page was pointed at a desk on purpose (?desk=…), so print there, with the model.
                  setPendingPhoto(file);
                  setStage("printing");
                  return;
                }
                void press(file);
              }}
            />
          </motion.div>
        ) : null}

        {stage === "converting" ? (
          <motion.section
            initial={reduce ? undefined : "hidden"}
            animate={reduce ? undefined : "shown"}
            variants={reveal}
            transition={{ duration: 0.5, ease: EASE }}
            className="panel rule mt-10 border p-8"
            data-testid="converting"
          >
            <p className="kicker">Step 1 · The press</p>
            <h2 className="display mt-3 text-4xl">Printing you into the city</h2>
            <p className="mt-3 max-w-[62ch] text-sm leading-relaxed text-[color:var(--color-muted)]">
              Everything below happens inside this page. Your photo is not uploaded anywhere, and there
              is no key or account in the path.
            </p>
            <ol className="mt-6 space-y-2" aria-live="polite">
              {stages.map((label) => (
                <li key={label} className="flex items-baseline gap-3 text-sm text-[color:var(--color-body)]">
                  <span style={{ color: "var(--color-gold)" }}>✓</span>
                  {label}
                </li>
              ))}
            </ol>
            <div className="rule mt-6 h-[3px] w-full overflow-hidden border" aria-hidden="true">
              <motion.div
                className="h-full"
                style={{ background: "var(--color-gold)" }}
                initial={{ width: "6%" }}
                animate={{ width: `${Math.min(94, 18 + stages.length * 19)}%` }}
                transition={{ duration: 0.45, ease: EASE }}
              />
            </div>
          </motion.section>
        ) : null}

        {stage === "printing" && pendingPhoto ? (
          <div className="mt-10">
            <PrintDesk file={pendingPhoto} choice={choice} onPrinted={printed} />
          </div>
        ) : null}

        {stage === "editing" && image ? (
          <motion.section
            initial={reduce ? undefined : { opacity: 0, y: 14 }}
            animate={reduce ? undefined : { opacity: 1, y: 0 }}
            transition={{ duration: 0.5, ease: EASE }}
            className="editor-shell panel rule mt-10 border p-8"
          >
            <div className="rule mb-5 flex items-center justify-between border-b pb-4">
              <div>
                <p className="kicker">Step 2</p>
                <h2 className="display mt-2 text-3xl">{plan.title}</h2>
              </div>
              <button
                type="button"
                data-testid="start-over"
                onClick={reset}
                className="lift rule border px-4 py-2 text-xs tracking-[0.2em] text-[color:var(--color-body)] uppercase hover:text-[color:var(--color-gold)]"
              >
                Start over
              </button>
            </div>
            <p className="mb-5 max-w-[62ch] text-sm leading-relaxed text-[color:var(--color-muted)]">
              Brief: {plan.brief}.
              {meta?.location ? <span> Printed at the {meta.location}.</span> : null}
              {plate?.kind === "plate" ? <span> (Using a cast plate.)</span> : null}
            </p>
            {source && image ? <BeforeAfter before={source} after={image} /> : null}
            {image ? (
              <div className="mt-5 flex flex-wrap items-center gap-3">
                <a
                  href={image}
                  download={frameName}
                  data-testid="download-frame"
                  className="lift border px-5 py-3 text-xs tracking-[0.2em] uppercase"
                  style={{ background: "var(--color-gold)", color: "var(--color-ink)", borderColor: "var(--color-gold)" }}
                >
                  Download this frame
                </a>
                <span className="kicker" style={{ color: "var(--color-muted)" }}>
                  clean PNG · no text, no watermark
                </span>
                {cut ? (
                  <span className="kicker" style={{ color: "var(--color-muted)" }}>
                    {cut.cutOut ? `you were cut out (${Math.round(cut.share * 100)}% of the frame)` : "whole frame painted"}
                  </span>
                ) : null}
              </div>
            ) : null}
            <EditorSurface surfaceId={plan.surfaceId} image={image} gating={plan.gating} onSaved={onSaved} />
          </motion.section>
        ) : null}

        {stage === "launch" && saved ? (
          <motion.div
            initial={reduce ? undefined : { opacity: 0, y: 14 }}
            animate={reduce ? undefined : { opacity: 1, y: 0 }}
            transition={{ duration: 0.5, ease: EASE }}
            className="mt-10"
          >
            <Launch
              artworkUrl={saved}
              location={meta?.location ?? null}
              onBackToEditor={() => setStage("editing")}
            />
          </motion.div>
        ) : null}
      </main>

      <footer className="rule mx-auto mt-16 max-w-[1280px] border-t px-8 py-8">
        <p className="kicker">Late Edition · Bahía Rosa</p>
        <p className="mt-3 max-w-[70ch] text-xs leading-relaxed text-[color:var(--color-faint)]">
          Unofficial fan-made project for the Unlayer Build with React Image Editor Challenge. Not
          affiliated with, endorsed by, or connected to Rockstar Games or Take-Two Interactive. All
          visuals are original work; the city (Bahía Rosa), its newspaper (LA GAVIOTA) and every
          placement it publishes into are invented. The print desk runs on your own machine: no
          account, no API key, and nothing you upload leaves it.
        </p>
      </footer>
    </div>
  );
}
