import { useCallback, useEffect, useState } from "react";
import { motion, useReducedMotion } from "motion/react";
import { EditorSurface, type ToolGating } from "./components/EditorSurface";
import { Launch } from "./components/Launch";
import { PlateGate, type PrintChoice } from "./components/PlateGate";
import { PrintDesk } from "./components/PrintDesk";
import type { PlateSource } from "./lib/plates/plates";
import { printChoices } from "./lib/printdesk/client";

/**
 * FIRST EDITION — the city's media machine.
 *
 * The shell follows the studio-site language measured in src/index.css: near-black canvas, deep
 * gradient panels, one gold accent, Art Deco display caps over a grotesque text face, and motion that
 * reveals rather than performs. Each stage is a surface, and each surface exposes a different tool set
 * in the editor — that gating is the level design (docs/editor-contract.md).
 */

const TITLE_GATING: ToolGating = { crop: true, resize: true, frame: true, text: true, filter: false, draw: false, shapes: false, stickers: false };
const PAGE_GATING: ToolGating = { crop: true, resize: true, filter: true, text: true, frame: false, draw: false, shapes: false, stickers: false };
const POSTER_GATING: ToolGating = { crop: true, resize: true, filter: true, text: true, frame: true, draw: true, shapes: true, stickers: true };

/** Which editor surface a printed style leads into, and what that surface asks for. */
const PLANS: Record<string, { surfaceId: string; title: string; brief: string; gating: ToolGating }> = {
  debut: { surfaceId: "loading", title: "the loading screen", brief: "clean grade, face centred, name plate clear", gating: TITLE_GATING },
  loadingscreen: { surfaceId: "loading", title: "the loading screen", brief: "painted panel — put your name in the clear band along the bottom", gating: TITLE_GATING },
  frontpage: { surfaceId: "frontpage", title: "the front page", brief: "face above the fold, masthead clear, tabloid drama", gating: PAGE_GATING },
  poster: { surfaceId: "poster", title: "the VIP poster", brief: "sell the room; you are the night's draw", gating: POSTER_GATING },
};

type Stage = "gate" | "printing" | "editing" | "launch";

const { locations } = printChoices();

/** The city's own plates — generated by tools/print-desk/scenery.mjs, scenery only, never a person. */
const CITY_ART = {
  boulevard: `${import.meta.env.BASE_URL}art/city/boulevard.jpg`,
  marina: `${import.meta.env.BASE_URL}art/city/marina.jpg`,
  downtown: `${import.meta.env.BASE_URL}art/city/downtown.jpg`,
};

const reveal = { hidden: { opacity: 0, y: 18 }, shown: { opacity: 1, y: 0 } };
const EASE = [0.22, 1, 0.36, 1] as const;

export function App() {
  const [stage, setStage] = useState<Stage>("gate");
  const [pendingPhoto, setPendingPhoto] = useState<File | null>(null);
  const [choice, setChoice] = useState<PrintChoice>({ surface: "debut", quality: false });
  const [plate, setPlate] = useState<PlateSource | null>(null);
  const [meta, setMeta] = useState<{ register: string; location: string | null; seed: number } | null>(null);
  const [saved, setSaved] = useState<string | null>(null);
  const reduce = useReducedMotion();

  const onSaved = useCallback((dataUrl: string) => {
    setSaved(dataUrl);
    setStage("launch");
  }, []);
  const image = plate ? (plate.kind === "photo" ? plate.objectUrl : plate.src) : null;
  const plan = PLANS[choice.surface] ?? PLANS.debut;

  const printed = useCallback(
    (next: PlateSource, printedMeta: { register: string; location: string | null; seed: number }) => {
      setPlate(next);
      setMeta(printedMeta);
      setStage("editing");
    },
    [],
  );

  const useFallback = useCallback(() => {
    // The payoff stage needs an artwork and the deployed build has no GPU: the city's own plate is
    // the honest stand-in — scenery, no person, nothing borrowed.
    setSaved(CITY_ART.marina);
    setMeta(null);
    setStage("launch");
  }, []);

  const reset = useCallback(() => {
    setPlate(null);
    setPendingPhoto(null);
    setSaved(null);
    setMeta(null);
    setStage("gate");
  }, []);

  // ?demo=launch — the tour without the model. The deployed build has no GPU, so a visitor (or a
  // judge) who cannot run the desk still gets to see the payoff: the city's own plate, launched into
  // the city. Same components, same exporter; only the artwork's provenance changes.
  useEffect(() => {
    const demo = new URLSearchParams(window.location.search).get("demo");
    if (demo === "launch") {
      useFallback();
      return;
    }
    // The editor without a GPU: the city's own plate stands in as the artwork, so the React Image
    // Editor surface (and its gating) can be seen, driven and tested on any machine.
    if (demo === "editor") {
      setPlate({ kind: "plate", id: "city-downtown", src: CITY_ART.downtown });
      setMeta(null);
      setStage("editing");
    }
  }, [useFallback]);

  return (
    <div className="grain vignette min-h-screen">
      <header className="rule sticky top-0 z-20 border-b bg-[color:var(--color-ink)]/85 backdrop-blur">
        <div className="mx-auto flex max-w-[1280px] items-center justify-between gap-6 px-8 py-4">
          <div className="flex items-baseline gap-4">
            <span className="wordmark text-3xl leading-none">Late Edition</span>
            <span className="kicker hidden sm:inline">Bahía Rosa · La Gaviota</span>
          </div>
          <div className="flex items-center gap-6">
            <span className="kicker hidden md:inline">{locations.length} places</span>
            <span className="kicker" style={{ color: "var(--color-gold)" }}>
              local desk
            </span>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-[1280px] px-8">
        <motion.section
          initial={reduce ? undefined : "hidden"}
          animate={reduce ? undefined : "shown"}
          variants={reveal}
          transition={{ duration: 0.7, ease: EASE }}
          data-testid="hero"
          className="rule relative mt-8 overflow-hidden border"
        >
          <div className="city-art" style={{ backgroundImage: `url(${CITY_ART.boulevard})` }} aria-hidden="true" />
          <div className="city-scrim" aria-hidden="true" />
          <div className="relative px-10 py-20">
            <p className="kicker">The city prints you</p>
            <h1 className="display mt-5 text-6xl sm:text-7xl">Late Edition</h1>
            <p className="mt-6 max-w-[52ch] text-base leading-relaxed text-[color:var(--color-body)]">
              Bring one photo. The desk — a model running on this machine, no account and no key —
              restyles you in the city&rsquo;s own light, at a place you choose. Then the editor turns
              that plate into tonight&rsquo;s poster, and the city runs it:{" "}
              <span className="text-[color:var(--color-paper)]">
                the billboard, the venue display, the feed, the postcard home
              </span>
              .
            </p>
            <div className="mt-10 flex flex-wrap items-center gap-x-8 gap-y-3">
              {["character shot", "loading screen", "front page", "poster", "billboard", "venue display", "postcard"].map((item) => (
                <span key={item} className="kicker" style={{ color: "var(--color-paper)" }}>
                  {item}
                </span>
              ))}
            </div>
          </div>
        </motion.section>

        <div className="rule mt-8 overflow-hidden border-y py-3">
          <div className="ticker kicker">
            {[...locations, ...locations].map((place, index) => (
              <span key={`${place.id}-${index}`} className="mx-6">
                {place.label} <span style={{ color: "var(--color-gold)" }}>·</span>
              </span>
            ))}
          </div>
        </div>

        {stage === "gate" ? (
          <motion.div
            initial={reduce ? undefined : "hidden"}
            whileInView={reduce ? undefined : "shown"}
            viewport={{ once: true, margin: "-80px" }}
            variants={reveal}
            transition={{ duration: 0.6, ease: EASE }}
            className="mt-10"
          >
            <PlateGate
              onPhoto={(file, picked) => {
                setPendingPhoto(file);
                setChoice(picked);
                setStage("printing");
              }}
            />
          </motion.div>
        ) : null}

        {stage === "printing" && pendingPhoto ? (
          <div className="mt-10">
            <PrintDesk file={pendingPhoto} choice={choice} onPrinted={printed} />
          </div>
        ) : null}

        {stage === "editing" && image ? (
          <motion.section
            initial={reduce ? undefined : { opacity: 0, y: 14 }}
            animate={reduce ? undefined : { opacity: 1, y: 0 }}
            transition={{ duration: 0.5, ease: EASE }}
            className="editor-shell panel rule mt-10 border p-8"
          >
            <div className="rule mb-5 flex items-center justify-between border-b pb-4">
              <div>
                <p className="kicker">Step 2</p>
                <h2 className="display mt-2 text-3xl">{plan.title}</h2>
              </div>
              <button
                type="button"
                data-testid="start-over"
                onClick={reset}
                className="lift rule border px-4 py-2 text-xs tracking-[0.2em] text-[color:var(--color-body)] uppercase hover:text-[color:var(--color-gold)]"
              >
                Start over
              </button>
            </div>
            <p className="mb-5 max-w-[62ch] text-sm leading-relaxed text-[color:var(--color-muted)]">
              Brief: {plan.brief}.
              {meta?.location ? <span> Printed at the {meta.location}.</span> : null}
              {plate?.kind === "plate" ? <span> (Using a cast plate.)</span> : null}
            </p>
            <EditorSurface surfaceId={plan.surfaceId} image={image} gating={plan.gating} onSaved={onSaved} />
          </motion.section>
        ) : null}

        {stage === "launch" && saved ? (
          <motion.div
            initial={reduce ? undefined : { opacity: 0, y: 14 }}
            animate={reduce ? undefined : { opacity: 1, y: 0 }}
            transition={{ duration: 0.5, ease: EASE }}
            className="mt-10"
          >
            <Launch
              artworkUrl={saved}
              location={meta?.location ?? null}
              onBackToEditor={() => setStage("editing")}
            />
          </motion.div>
        ) : null}
      </main>

      <footer className="rule mx-auto mt-16 max-w-[1280px] border-t px-8 py-8">
        <p className="kicker">Late Edition · Bahía Rosa</p>
        <p className="mt-3 max-w-[70ch] text-xs leading-relaxed text-[color:var(--color-faint)]">
          Unofficial fan-made project for the Unlayer Build with React Image Editor Challenge. Not
          affiliated with, endorsed by, or connected to Rockstar Games or Take-Two Interactive. All
          visuals are original work; the city (Bahía Rosa), its newspaper (LA GAVIOTA) and every
          placement it publishes into are invented. The print desk runs on your own machine: no
          account, no API key, and nothing you upload leaves it.
        </p>
      </footer>
    </div>
  );
}
